name: ShiftLeft Scan
on:
  push:
    branches:
      - master
      - feature/*
  schedule:
  - cron: "0 */4 * * *"

jobs:
  Scan_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Security scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
        output: reports
        type: credscan,python,depscan
      env:
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: scan-reports
        path: reports

